services:
  runner:
    build:
      context: ./runner
    container_name: k6-runner
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    networks:
      - k6net

  backend:
    build:
      context: ./Services
    container_name: k6-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - prometheus
      - runner
    environment:
      - BACKEND_PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=loadtest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TEMPORAL_SERVICE_ADDRESS=host.docker.internal:7233
      - PROMETHEUS_HEALTH_URL=http://prometheus:9090/-/healthy
      - PROMETHEUS_URL=http://prometheus:9090
      - RUNNER_HEALTH_ADDR=runner:8080
      - RUNNER_URL=http://runner:8080/run-test
    networks:
      - k6net
    volumes:
      - ./Services/results:/app/results

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loadtest
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - k6net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - k6net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards/json:ro
    networks:
      - k6net

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:

networks:
  k6net:
    driver: bridge
